### ISSUE TITLE
Add a Gemfile to project

### ISSUE THREAD

**Issue by Debilski** [scala/scala.github.com#109]
Having a `Gemfile` (α) in the root directory with a content as follows:

    source :rubygems

    gem "jekyll"
    gem "RedCloth"

would make installation for users of [bundler](http://gembundler.com) much easier.

    # Installs all required gems into a local folder (β)
    # Without --path it will try to install globally
    $ bundle install --path=vendor/

    # Run local version of jekyll 
    $ bundle exec jekyll

In the long run this means less version conflicts and less binaries in $PATH.

(α) For build stability, Gemfile.lock could also be checked in. This will fix the version number of every gem.
(β) One might need to exclude vendor/ from Jekyll’s build system then.

**Comment by SethTisue** [comment]
this was done in 925c713ca4c6368fd389633fb61ed58e1209ad4b
