### ISSUE TITLE
There should be a way to link directly to a Glossary entry

### ISSUE THREAD

**Issue by swartzrock** [scala/scala.github.com#172]
The Scala Glossary is excellent, I just wish there was a way to link directly to one of its entries.

For example, when writing it would be great to link directly to the entry for "function literal" like this:
http://docs.scala-lang.org/glossary/#function_literal

Unfortunately this link just resolves to the top level of the glossary. Can this be fixed to support direct links to glossary entries?

**Comment by SethTisue** [comment]
#354 was merged
