### ISSUE TITLE
[documentation] HashMap foreach signature listed as iterating over keys, when really it iterates over key value pairs

### ISSUE THREAD

**Issue by makoConstruct** [scala/scala.github.com#386]
http://www.scala-lang.org/api/current/index.html#scala.collection.immutable.HashMap@foreach(f:A=>Unit):Unit
http://www.scala-lang.org/api/current/index.html#scala.collection.mutable.HashMap@foreach(f:A=>Unit):Unit

The source code for the HashMap -both mutable and immutable- does not agree with this.

**Comment by SethTisue** [comment]
if this is still an issue, please open a ticket at https://issues.scala-lang.org (or submit a PR to https://github.com/scala/scala/pulls)
