### ISSUE TITLE
GitHub Pages builds keep failing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#442]
since merging https://github.com/scala/scala.github.com/issues/406 I have been unable to get the change (which is quite small and innocent) to show up on [the site](http://docs.scala-lang.org/tutorials/tour/case-classes.html). I've pushed several empty commits to force rebuilds, but all have failed. in the three failures so far, spread over about a day, the error message has been a little different each time:

* "Page build failed"
* "POSIX::Spawn::TimeoutExceeded"
* "page build timed out. Please try again later." 

I don't know if GitHub Pages is just having transient trouble that will fix itself, or what.

Jekyll builds the site just fine locally.

**Comment by heathermiller** [comment]
Check to see that the version of Jekyll that you're using is what Github Pages is using.

**Comment by SethTisue** [comment]
Rachel at GitHub support says:

>We're working on resolving a problem with the Pygment highlighter timing out at random on a number of Pages repos. Our engineers are working on resolving this right now. I've manually triggered a rebuild of your repo and it seems to have worked. So sorry for the trouble! In the meantime, if it happens again, can you try pushing an arbitrary commit to trigger a rebuild? And of course, let us know if this persists again. Sorry about that!

and yeah, I see the change on the site now.

but anyway you're right Heather, I should make my local Jekyll environment match the server one; right now it doesn't. this is on my to-do list now.

**Comment by SethTisue** [comment]
I think we can assume this is resolved.
