### ISSUE TITLE
Footer doesn't always stick to bottom

### ISSUE THREAD

**Issue by heathermiller** [scala/scala.github.com#48]
For example, in the Scala Style Guide.

**Comment by SethTisue** [comment]
@heathermiller is this a problem anymore?

**Comment by kzys** [comment]
A shorter page still has an issue. I'm not sure that's what the issue meant though.
http://docs.scala-lang.org/style/overview.html

**Comment by SethTisue** [comment]
I'm going to close this one since we don't know what it is.

@kzys, if you see a problem on that page, can you open a new ticket that describes it? I opened that page and didn't see what the problem was.

**Comment by kzys** [comment]
Sure. #678
