### ISSUE TITLE
Example exhibits integer overflow/incorrect result silently

### ISSUE THREAD

**Issue by sfaleron** [scala/scala.github.com#480]
In https://github.com/scala/scala.github.com/blob/master/overviews/parallel-collections/overview.md, under "Some Examples", the fold/sum example overflows.

One might choose a smaller range, or point out the gotcha for the unwary.

    scala> (1 to 1e6.toInt).map(_.toLong).sum
    res42: Long = 500000500000

**Comment by SethTisue** [comment]
nice catch! can I interest you in submitting a pull request with a fix?

**Comment by sfaleron** [comment]
I'll give it a go.  I'm not familiar with pull requests, but I need to learn :)

**Comment by SethTisue** [comment]
cool. help is available at https://gitter.im/scala/contributors

**Comment by sfaleron** [comment]
Anything further I need to do? Did I miss anything?

**Comment by SethTisue** [comment]
merged!
