### ISSUE TITLE
The text is displayed as a code snippet in the zh-cn documentation

### ISSUE THREAD

**Issue by harry0000** [scala/scala.github.com#485]
There is a problem that the text is displayed as a code snippet in the "Value Classes and Universal Traits" page because of that there is no line break after syntax highlighting.

**English**
http://docs.scala-lang.org/overviews/core/value-classes.html#examples-of-limitations

![en](https://cloud.githubusercontent.com/assets/3132512/12317036/5eea9770-bad0-11e5-8c09-1a47ef9d59d3.png)

**zh-cn**
http://docs.scala-lang.org/zh-cn/overviews/core/value-classes.html#section-8

![cn](https://cloud.githubusercontent.com/assets/3132512/12317038/64a2205c-bad0-11e5-8d13-e6197cdc6c4b.png)

**Comment by SethTisue** [comment]
thanks for the report. can I interest you in submitting a pull request with a fix...?

**Comment by harry0000** [comment]
I tried to just fix markdown syntax! But I did not check the validity of translation. (Because I am not a Chinese speaker).
