### ISSUE TITLE
Yup, Jekyll 3 complains about our Gemfile.lock now

### ISSUE THREAD

**Issue by heathermiller** [scala/scala.github.com#495]
When merging OK PRs, GitHub now emails me this warning upon page build:
(It's so nice of them to email us now!! I can't even believe it)

> The page build completed successfully, but returned the following warning:
> 
> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.
> 
> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:
> 
>   https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
> 
> If you have any questions you can contact us by replying to this email.

As mentioned, I think this is some useless thing in the Gemfile.lock that somehow got added, as we're not using any static syntax highlighting at all (it all happens in js, with Google's prettify).

@SethTisue, by any chance could you have a look at this? Is it kosher to just remove pygments from the Gemfile.lock?

**Comment by dwijnand** [comment]
Feel free to refer to me upgrading the ENSIME docs setup: https://github.com/ensime/ensime.github.io/pull/42/files

**Comment by dwijnand** [comment]
Sorry, also note the updates to ENSIME's `_config.yml`: https://github.com/ensime/ensime.github.io/commits/master/_config.yml

**Comment by SethTisue** [comment]
> Is it kosher to just remove pygments from the Gemfile.lock?

I think so. `bundler update github-pages` did so automatically. see #496

**Comment by SethTisue** [comment]
> I think this is some useless thing in the Gemfile.lock that somehow got added

fwiw, it stemmed from `_config.yml`, actually. #496 modifies `_config.yml` as follows:

```diff
-highlighter: pygments
+highlighter: rouge
```

it's certainly possible we don't need that line at all, but I don't think it's harmful, either.

**Comment by SethTisue** [comment]
thanks @dwijnand — this was helpful for sanity-checking
