### ISSUE TITLE
Java's naming convention for constants is not UpperCamelCase

### ISSUE THREAD

**Issue by solimant** [scala/scala.github.com#512]
On the "Naming Conventions" doc page, it says in the [Constants, Values, Variable and Methods](http://docs.scala-lang.org/style/naming-conventions.html#constants-values-variable-and-methods) that: 

> Constant names should be in upper camel case... (similar to Java’s static final members)

Java does not follow upper camel case for constants naming convention, according to the [Code Conventions for the Java TM Programming Language](http://www.oracle.com/technetwork/java/codeconventions-135099.html):

> The names of variables declared class constants and of ANSI constants should be all uppercase with words separated by underscores ("_").

**Comment by SethTisue** [comment]
it's defining what is "considered a constant" in this context, not asserting something about the Java convention for constants.

nonetheless, if that wasn't clear to you, that probably means the text should be altered to be clearer. a PR with a proposed improvement would be welcome.
