### ISSUE TITLE
lengthCompare is said in doc to take seq as param but does not

### ISSUE THREAD

**Issue by bjornregnell** [scala/scala.github.com#515]
Here:
http://docs.scala-lang.org/overviews/collections/seqs.html
This example is given:

xs.lengthCompare ys  "Returns -1 if xs is shorter than ys, +1 if it is longer, and 0 is they have the same length. Works even if one if the sequences is infinite."

(BTW: the example should not have a dot in operator syntax)

When I do this:
$ scala
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_66).
Type in expressions for evaluation. Or try :help.

scala> val xs = (1 to 10).toVector
xs: Vector[Int] = Vector(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

scala> xs lengthCompare 10
res0: Int = 0

scala> xs lengthCompare xs
<console>:13: error: type mismatch;
 found   : Vector[Int]
 required: Int
       xs lengthCompare xs
                        ^
Is the method signature wrong or is the overview doc wrong? Should the parameter be an Int or another sequence?
I can try to fix it, if it is the overview doc, with some guidance of how to...

**Comment by odersky** [comment]
Hi Bjoern,

The overview doc is wrong. Maybe it would make sense to add a variant that
corresponds to the overview doc, but right now it's not there.

Thanks for noticing! To fix it, the process is to do a PR against the
Scala-lang doc site (repo is git@github.com:scala/scala-lang.git).

Thanks,

 - Martin

On Thu, Apr 7, 2016 at 8:38 PM, Bjorn Regnell <notifications@github.com>
wrote:

> Here:
> http://docs.scala-lang.org/overviews/collections/seqs.html
> This example is given:
>
> xs.lengthCompare ys "Returns -1 if xs is shorter than ys, +1 if it is
> longer, and 0 is they have the same length. Works even if one if the
> sequences is infinite."
>
> (BTW: the example should not have a dot in operator syntax)
>
> When I do this:
> $ scala
> Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_66).
> Type in expressions for evaluation. Or try :help.
>
> scala> val xs = (1 to 10).toVector
> xs: Vector[Int] = Vector(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
>
> scala> xs lengthCompare 10
> res0: Int = 0
>
> scala> xs lengthCompare xs
> :13: error: type mismatch;
> found : Vector[Int]
> required: Int
> xs lengthCompare xs
> ^
> Is the method signature wrong or is the overview doc wrong? SHould the
> parameter be an Int or another sequence?
> I can try to fix it, if it is the overview doc, with some guidance of how
> to...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scala/scala.github.com/issues/515>
>



-- 

Martin Odersky
EPFL and Lightbend

**Comment by heathermiller** [comment]
Correction: the documentation repo is git@github.com:scala/scala.github.com.git (you're posting an issue in the correct one)
But yes! The easiest fix would be to update the documentation, so a PR against this repo would be very much appreciated!

**Comment by bjornregnell** [comment]
Ah! Thanks - was just about to double check :)
