### ISSUE TITLE
Is (Can) the language spec of 2.11 (be) available in pdf?

### ISSUE THREAD

**Issue by bjornregnell** [scala/scala.github.com#516]
(Not sure if this is the place to put this issue, but issues were not activated on 
https://github.com/scala/scala/tree/2.11.x/spec
)
I have tried to find the language spec of Scala 2.11 by searching the web but only found 2.9.
https://www.google.se/search?q=scala+language+specification+2.11+pdf  

It would be really nice to have a link to the spec in pdf from the doc site here 
http://www.scala-lang.org/files/archive/spec/2.11/ 
to enable linear, offline read and especially global find ctrl+F in the whole specification...

**Comment by SethTisue** [comment]
adding PDF generation to the spec build process would be a very welcome community contribution

**Comment by smarter** [comment]
This does not seem trivial, last time I looked into it I found https://peterlu.github.io/2014/08/03/markdown_latex_pdf.html which compares some approaches.

**Comment by bjornregnell** [comment]
It says here https://github.com/scala/scala.github.com that kramdown is used and here I get the impression from the image here http://kramdown.gettalong.org/ that pdf comes out of the thing... I have no experience of this, but if the kramdown ruby app produces both latex and pdf, maybe that can be added to the build process?

Even if the pdf output is not perfect, it will still enable global search and offline reading...

**Comment by jarrodwb** [comment]
The spec is not provided in this repo so I think that this issue should be migrated to the https://github.com/scala/scala issue tracker. They don't use GitHub Issues though. The readme of the repo does point to a Jira issue tracker which can be found at https://issues.scala-lang.org . I think this issue should be migrated there.

In general though I do like the idea of having a more flexible way of building the tutorials and other content on this site but that is a different issue and can be disused elsewhere.

**Comment by SethTisue** [comment]
also a JIRA issue at https://issues.scala-lang.org/browse/SI-10218

**Comment by SethTisue** [comment]
let's keep scala/bug#10218 as the issue of record on this. making this happen would require action in multiple repos (scala/scala first, then scala/scala-lang), but scala/scala.github.com isn't one of them
