### ISSUE TITLE
Improvement/Rewrite for Case Class tutorial/tour

### ISSUE THREAD

**Issue by jtcwang** [scala/scala.github.com#547]
I'm talking about [this page](http://docs.scala-lang.org/tutorials/tour/case-classes.html).

Case class is probably one of the best features of Scala and heart-winner for anyone interested to Scala, but I feel like the current documentation doesn't do it justice. The comment section of that article echos my feeling that it's not really beginner friendly.

Here are the improvements that I think we can make, assuming that the majority of our audience is from an imperative background:

* Better example
  * Most of the people looking at that page won't be familiar with parsing. Switching over to real world 'objects' may help a lot so they don't have to wonder what `App` and `Fun` means
* Show the equivalent java code (e.g. generated `hashCode`, `equals` etc etc)
  * Show how succinct Scala is!

If people is happy with my proposal, I'll go ahead and make it happen.

**Comment by SethTisue** [comment]
I support both of your proposed changes.

**Comment by jtcwang** [comment]
I didn't end up showing the equivalent Java code. I'm not sure whether it'll make the post too long-winded. I can add it if you think it's helpful.

**Comment by SethTisue** [comment]
can you make a pull request and let's discuss there?

**Comment by jtcwang** [comment]
Oh sorry. The PR has already been made (#599). I'll move my comment there.
