### ISSUE TITLE
SIP-12 Uncluttering Scala’s syntax for control structures

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#555]
[SIP-12](http://docs.scala-lang.org/sips/pending/uncluttering-control.html), from 2011, predates the establishment of the new SIP process, so previous history and discussion is on the above-linked page, including in some extensive Disqus comments.

**Comment by SethTisue** [comment]
The SIP was taken up again at the August 2016 SIP meeting.

The original proposer @odersky couldn't attend, so he couldn't weigh in. (And if he's recently expressed an opinion about this SIP elsewhere, I'm not aware of it.)

I presented my review in the meeting. My main points were:

* there is no clear consensus that this change is desirable. in discussions, some are for, others against
* the major downsides are:
    * it makes Scala look and feel noticeably less like Java and other C-like languages; we generally avoid this unless there's a big win
    * significant migration pain for users would be involved, even more so in 2016 than 2011
    * even if you like the proposed syntax (many do, including committee members), it's unclear that the actual benefits of the change are really that big
* has anything changed since 2011? not a whole lot
    * the community isn't clamoring for this as far as I know. I very rarely see it get brought up in discussions, at conferences, etc.
    * the Dotty project exists now, but they haven't gone down this path
    * development has (only very recently) begun at the Scala Center on a code-rewriting tool that would help migration

In the ensuing discussion, there was a bit of confusion over whether the old syntax would continue to be supported, and if so, if adding more ways to express the same thing was bad. But note that the migration plan in the proposal does not recommend supporting the old syntax indefinitely; rather, it would be supported only during a deprecation period.

Regardless, the consensus was against the proposal, for the basic reasons given above (discussed in more detail in the meeting video). "This ship sailed years ago" (@adriaanm), "is it really improving things that much... what do we get for it" (@heathermiller).

@jvican and @jsuereth pointed out that in addition to the obvious migration pain of users needing to update their code, there would be pain for the makers of tools such as IDEs and the proposed code-rewriting tool. @adriaanm pointed out that even if an automatic code-writing tool existed, so you still have the universal pain of having the needed changes cluttering up the version control history of every Scala project.

The committee (minus @odersky, @sjrd, and @non who weren't present) voted unanimously to reject. (We briefly addressed the possibility of marking it as "postpone" since it seems at least theoretically possible it could happen in some future sweeping language redesign, but it seems simpler to just reject.)

**Comment by nafg** [comment]
> significant migration pain for users would be involved, even more so in 2016 than 2011
Another difference might be that in 2011, ruby and python were more popular while in 2016 javascript is,  so I think appeal to people using or considering other languages is greatly reduced.

**Comment by SethTisue** [comment]
@jvican should this PR be closed?

**Comment by SethTisue** [comment]
closing, fyi @jvican

**Comment by jvican** [comment]
Thanks @SethTisue!

**Comment by the-Arioch** [comment]
> SIP-12, from 2011, predates....

this URL was 404ed

Guess would be great if there to be some SIP index with permalinks

-----------

Personally i also dislike C-ish syntax, especially dangerous assignment operator.
But... i think tweaking language syntax now is possible using compiler plugins instead.

**Comment by SethTisue** [comment]
for the record, the new URL is http://docs.scala-lang.org/sips/pending/uncluttering-control.html (and changing the URLs isn't a good scheme, which I've reported as #585)

> Guess would be great if there to be some SIP index with permalinks

there is, http://docs.scala-lang.org/sips/sip-list.html

**Comment by the-Arioch** [comment]
Yep, i found it. I meant computer-maintained db like http://docs.scala-lang.org/sips/by-id/SIP-12
