### ISSUE TITLE
URL change when SIP is accepted or rejected breaks links everywhere

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#585]
so e.g. SIP-12 is now http://docs.scala-lang.org/sips/rejected/uncluttering-control.html , which means that everyone who had linked to the old URL http://docs.scala-lang.org/sips/pending/uncluttering-control.html now has a broken link on their hands

if we are going to change the URLs, we should redirect. probably better/easier not to change them in the first place

reported by @the-Arioch at https://github.com/scala/scala.github.com/issues/555 /cc @jvican

**Comment by jvican** [comment]
True. Didn't realise this changed the urls. How would you propose to redirect?

**Comment by SethTisue** [comment]
maybe @fsalvi knows

**Comment by fsalvi** [comment]
docs.scala-lang.org is hosted on github, so I don't have any control on it. Sorry...

**Comment by jvican** [comment]
OK, will look into this when I've got some time, and see if it's possible. The problem here is how Jekyll is set up.

**Comment by dwijnand** [comment]
An empty html file with a javascript redirect?

**Comment by jarrodwb** [comment]
It would be simple to just add the status as a variable in the YAML header. There is no need to have the URL involved. If you want a list of rejected or accepted then just use a layout that loops through the pages and pulls out the ones you want.

If we adopt this approach this should fix the problem going forward. We would still have to deal with the broken URLs that are out in the wild.

**Comment by jvican** [comment]
Yeah, this is what I had in mind, although the fact that the SIPs won't be in folders will change all the existing links, since Jekyll appends the folder name to the final URL. We'll need a way to tell Jekyll to use that header field to build the URL.

**Comment by the-Arioch** [comment]
Being a total bystander with no internal knowledge on what is implementable i can see two potential approaches.

Approach Explicit:

1. For every SIP there should be created a permalink based upon the id, something like

http://docs.scala-lang.org/sips/by-id/SIP-12

2. When a new SIP is uploaded some bot should check if it is already registered in that centralized db and insert it or update the destination URL of it.

It also should ( after checking it was not done yet ) and modify the very text of that page, inserting easily visible permalink notice and URL early on, maybe right below the title or a bit further, but anyway withing the first not-scrolled briwser window view port.

That wouldn't fix the URL 's already astray, woukd depend upon human attention, but would provide for making permalinks for future SIPs or when fixing missing links.

Option Implicit

2. Some kind of HTTP level redirect rule, so initial

http://docs.scala-lang.org/sips/rejected/uncluttering-control.html 

Would get auto changed to

 http://docs.scala-lang.org/sips/rejected/SIP-12_uncluttering-control.html

or even

http://docs.scala-lang.org/sips/rejected/SIP-12/uncluttering-control.html

This perhaps can be implemented by some bot, renaming files.

Then the web server would need to be set up to check for explicit ID in the URL and to ignore the folder if one was found.

It would have to "pattern-match" URLs like
http://docs.scala-lang.org/sips/***/{ID}_***.html

While it might be impossible on github, maybe you could set some standalone simplistic web server to only provide links to those SIPs, and either embedding final documents into IFRAME or making HTTP redirect ( the one that should not change the URL in the browser, don't remember if that is 303 or 304). As a last chance there can be a forward-proxy that would fetch pages from github and retransmit.

**Comment by the-Arioch** [comment]
Since it is"hosted on github" maybe tweaking Jekyll can be sidestepped and a dedicated robot working on git/files level can be made to update those Jekyll-affected pages after the fact

**Comment by the-Arioch** [comment]
> empty html file with a javascript redirect?

No need for scripts. Plain HTML suffice.

Check HTML/HEAD/META tag
You need something like "http-equiv" with "reload" or "redirect" parameter, which are seconds that can be tagged with new final URL

Don't quite remember, did it too far ago

**Comment by jvican** [comment]
Great explanation. Maybe this is what we're looking for? https://github.com/jekyll/jekyll-redirect-from/blob/master/README.md

It's simpler and already ready to use.

**Comment by heathermiller** [comment]
There are already a bunch of SIP redirects in the `/sip` directory. Why not just add another?

**Comment by heathermiller** [comment]
E.g., https://github.com/scala/scala.github.com/blob/master/sips/pending/value-classes.html

**Comment by the-Arioch** [comment]
http://scala.github.com/sips/pending/value-classes.html - seems to work

**Comment by jvican** [comment]
I'm submitting a PR soon with [https://github.com/jekyll/jekyll-redirect-from/blob/master/README.md](https://github.com/jekyll/jekyll-redirect-from/blob/master/README.md). It's exactly the same as putting a HTML redirect file as we're doing now, but without the manual process.
  
I'm choosing this solution as it's the easiest to implement and the more comfortable for me in the future (I'm intensively editing the SIP proposals). In the future, we can explore the id approach.
