### ISSUE TITLE
Collections Architecture Doc wrongly has Spanish link

### ISSUE THREAD

**Issue by heathermiller** [scala/scala.github.com#60]
See: http://docs.scala-lang.org/overviews/core/architecture-of-scala-collections.html

There should be no Spanish flag indicating that a Spanish translation exists-- because one doesn't.

**Comment by jarrodwb** [comment]
There is a lot of these. I think these are some examples.

http://docs.scala-lang.org/ja/overviews/reflection/changelog211
http://docs.scala-lang.org/ja/overviews/macros/changelog211
http://docs.scala-lang.org/ja/overviews/quasiquotes/intro.html
http://docs.scala-lang.org/tutorials/FAQ/tutorials/FAQ/finding-implicits.html
http://docs.scala-lang.org/ko/tutorials/tour/singleton-objects
http://docs.scala-lang.org/ko/tutorials/tour/implicit-conversions
http://docs.scala-lang.org/ja/overviews/reflection/names-exprs-scopes-more.html
http://docs.scala-lang.org/ja/overview/macros/overview.html
http://docs.scala-lang.org/es/tutorials/tour/unified_types.html
http://docs.scala-lang.org/tutorials/tour/default_parameter_values.html
http://docs.scala-lang.org/tutorials/tour/views
http://docs.scala-lang.org/ba/tutorials/tour/views
http://docs.scala-lang.org/es/tutorials/tour/views

There is at least one bug in the _layout files. I have not found it yet though. I have been going though the site to find dead links.

**Comment by kzys** [comment]
Fixed?

Now http://docs.scala-lang.org/overviews/core/architecture-of-scala-collections.html has only English and Chinese, which exists.

**Comment by SethTisue** [comment]
indeed, seems fixed
