### ISSUE TITLE
Unexpected advertisements on scala documentation pages

### ISSUE THREAD

**Issue by tobym** [scala/scala.github.com#603]
Looks like the Disqus comment plugin is inserting large blocks of advertising on Scala documentation pages (e.g. http://docs.scala-lang.org/tutorials/tour/implicit-parameters.html).  This is rather jarring and probably not desired for official pages like that.

![unexpected ads on doc pages](https://pbs.twimg.com/media/Cu8QT-wXEAA38ZY.jpg:large)

**Comment by tobym** [comment]
It appears that ads can be turned off by whoever has admin on scala-lang's disqus account (https://help.disqus.com/customer/en/portal/articles/2542532-how-to-disable-reveal-ads-)

**Comment by jarrodwb** [comment]
We should fix this. I think it should be a very high priority.

**Comment by SethTisue** [comment]
yeah, this is pretty bad. I'll try to get to it within the next 24 hours

**Comment by heathermiller** [comment]
Done. 

As usual, Disqus turned this on without informing/asking us first. (This is the second time they've done this, if IIRC). Fun fact though, apparently Disqus pays us for displaying ads on our pages. We apparently earned $24.57 for torturing people with ads :unamused:

**Comment by heathermiller** [comment]
PS, apparently it takes some time to "deactivate" according to Disqus :expressionless:

**Comment by jarrodwb** [comment]
Perfect! Thanks.
