### ISSUE TITLE
enable `-Xfatal-warnings` in `tut`?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#606]
this would catch things like inadvertent/leftover use of postfix syntax (e.g. #605). it would catch all sorts of things we want caught, really

I hope there wouldn't be a lot of false negatives — my guess is that it would be fine. lots of real projects are able to adhere to `-Xfatal-warnings`

**Comment by jarrodwb** [comment]
https://travis-ci.org/jarrodwb/scala.github.com/builds/169330245

I got `tut` to fail on a branch I am working on. It makes sense to me to fix the problems before I make a pull request. I think we need to merge in #605 first and also take a look at and fix `tutorials/tour/implicit-conversions.md`. It also throws an error.

**Comment by jarrodwb** [comment]
I am off to bed but thanks for the fast track on #605. See you tomorrow.

**Comment by SethTisue** [comment]
fixed in #608
