### ISSUE TITLE
Sets are not PartialFunctions

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#619]
http://docs.scala-lang.org/overviews/collections/trait-iterable.html#comment-2985923809 falsely claims a `Set` is a `PartialFunction`

reported by a visitor at http://docs.scala-lang.org/overviews/collections/trait-iterable.html#comment-2985923809

**Comment by Philippus** [comment]
This one can be closed I think.

**Comment by SethTisue** [comment]
why can it be closed?

**Comment by Philippus** [comment]
part of https://github.com/scala/scala.github.com/pull/719

**Comment by SethTisue** [comment]
👍
