### ISSUE TITLE
Code samples in language tour should not use JAVA_STYLE_CONSTANTS

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#633]
e.g. at http://docs.scala-lang.org/tutorials/tour/case-classes, but perhaps there are others

Scala style is `LikeThis`, not `LIKE_THIS`

**Comment by Philippus** [comment]
The new tour doesn't have these anymore, so I think this issue can be closed.

**Comment by heathermiller** [comment]
Thanks :)
