### ISSUE TITLE
site builds are timing out

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#680]
after my last PR merge I got an email from GitHub:

> The page build failed with the following error:
> Page build timed out. Please try again later.

I assume it's https://github.com/scala/scala.github.com/issues/607 as usual, except that now that we have more translations, the problem has gotten to the point where it's tipped over some threshold, and now we can't push updates to the site at all.

**Comment by SethTisue** [comment]
probably it's the same reason Travis has been really flaky lately — Travis has a timeout too, I think we're over that one as well, now, at least most of the time

**Comment by jvican** [comment]
Same in https://github.com/scala/scala.github.com/pull/674#discussion_r100371770.

**Comment by jvican** [comment]
And https://github.com/scala/scala.github.com/pull/679.

**Comment by jvican** [comment]
https://github.com/scala/scala.github.com/commit/ee72508e5520d5cc6a2a71d8d51065183d6120cf did not fix this issue. I'm starting to give up on Travis, I think I'll add this repository to the Scala Platform CI which is much more powerful than Travis, and hopefully we'll get faster build times too.

**Comment by SethTisue** [comment]
there is no reason to anticipate the build times would be any faster on a different service or machine; it is just as slow in local runs on a fast machine. Drone vs Travis isn't important to me either way, but what we actually need is a fix for #607

**Comment by heathermiller** [comment]
I guess @jvican's point is that we could run our builds on machines that we control, where we don't have to worry about timeouts.

Regardless, I think @travis032654 will have a look at this issue (#607) during his work on cleaning up some of the documentation.

**Comment by heathermiller** [comment]
Hmm. For what it's worth, I just received a site build failure too. I misunderstood your original issue and thought you were referring to CI only. But now it seems GitHub is timing out our builds as well. 

For the record, this is what I received from GitHub via email:

> The page build failed with the following error:
>
> Page build timed out. Please try again later.
>
> For information on troubleshooting Jekyll see:
>
>  https://help.github.com/articles/troubleshooting-jekyll-builds
>
> If you have any questions you can contact us by replying to this email.

Maybe it's time we (1) speed things up via one of the suggestions made in #607, and (2) put this build on the same machine that builds scala-lang. (/cc @fsalvi, just to keep you in the loop)

**Comment by jvican** [comment]
Fixed, see https://github.com/scala/scala.github.com/pull/685#issuecomment-279388338.
