### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by som-snytt** [scala/scala.github.com#720]
It would be nice if hygiene were maintained with respect to old, very narrow branches.

Branches communicate activity in the project, so they should not introduce noise.

**Comment by SethTisue** [comment]
GitHub has a nice UI for this: https://github.com/scala/scala.github.com/branches

**Comment by SethTisue** [comment]
I deleted all already-merged branches.

@jvican can we delete your `spores-annoncement` branch?

@heathermiller can we delete your old branches? (all are either 2 years or 4 years old)

**Comment by jvican** [comment]
@SethTisue Please do.

**Comment by SethTisue** [comment]
@jvican done

@heathermiller ping?

**Comment by heathermiller** [comment]
I have no idea what stale branches I have. Totally fine to delete anything you find haha, sorry!

**Comment by SethTisue** [comment]
💥
