### ISSUE TITLE
Weirdly dark, grey background on some pages

### ISSUE THREAD

**Issue by ryan-williams** [scala/scala.github.com#767]
http://docs.scala-lang.org/overviews/

![](https://cl.ly/2c3R3l0T103V/Screen%20Shot%202017-05-02%20at%209.06.57%20PM.png)

LIkewise http://docs.scala-lang.org/tutorials/

![](https://cl.ly/1Z1t1M1s3u0a/Screen%20Shot%202017-05-02%20at%209.08.53%20PM.png)

It looks like the page is greyed out while a modal popup requires action, but afaict there's no such popup, it's just a weirdly dark/low-contrast color scheme.

Most links go to pages with a saner/lighter scheme, e.g. http://docs.scala-lang.org/tutorials/tour/tour-of-scala.html

![](https://cl.ly/252J0m2s1H1U/Screen%20Shot%202017-05-02%20at%209.09.37%20PM.png)

**Comment by eed3si9n** [comment]
I've never questioned it until this moment, but I'm now ruined. +1

**Comment by heathermiller** [comment]
Back in 2010 when this site was made, index pages were meant to be grey. Documentation pages were meant to be white.

I agree that in 2017 this isn't visually appealing. But this isn't a bug per se. At least it shouldn't be an issue in Github. @travissarles has applied the new website design (in scala-lang/#606) to this repo.

**Comment by ryan-williams** [comment]
OK, let me know if there's somewhere else a thing like this should be filed.

I sent #768 to change it in case that is useful.
