### ISSUE TITLE
broken link on mixins page

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#771]
reported by a user at http://docs.scala-lang.org/tutorials/tour/mixin-class-composition.html#comment-3302979592

**Comment by Philippus** [comment]
Is the link broken or is the topic missing?

**Comment by SethTisue** [comment]
yeah I wouldn't be surprised if the one-PR-at-a-time merging of the various tour revisions has resulted in similar breakage throughout

**Comment by SethTisue** [comment]
(over in scala-lang, we have a Travis build https://github.com/scala/scala-lang/blob/master/.travis.yml which catches at least some of these things before they happen, it would be really helpful to have something similar in this repo)

**Comment by SethTisue** [comment]
I forgot we use Drone, not Travis, in this repo. but, I don't know why the Drone build didn't catch this bug.

**Comment by SethTisue** [comment]
@travissarles this is being reported over and over again in the Disqus comments on the page — could you prioritize a fix?

**Comment by Philippus** [comment]
@SethTisue there you go.

**Comment by travissarles** [comment]
@SethTisue it looks like my changes from 4 days ago fixed it. Are you still seeing it?

**Comment by SethTisue** [comment]
@Philippus fixed it in #788
