### ISSUE TITLE
add a Travis-CI build for validating pull requests

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#782]
we have had this over in scala/scala-lang since https://github.com/scala/scala-lang/pull/378 was merged

the latest config in that repo is https://github.com/scala/scala-lang/blob/master/.travis.yml (and could perhaps largely be just copied over to here?)

**Comment by SethTisue** [comment]
this came up recently at e.g. https://github.com/scala/scala.github.com/issues/771 which I think Travis could have caught

**Comment by SethTisue** [comment]
@travissarles unless you think having two Travises here would be too confusing 😁

**Comment by travissarles** [comment]
I think it's a good idea if we're going to keep the repos separate.

**Comment by SethTisue** [comment]
In the long run, I would still like to see the two repos consolidated. But I assume that's still far enough off (though getting closer!) that this is still very much worth doing in the meantime.

**Comment by travissarles** [comment]
Yes, I had talked about consolidation with @heathermiller but we decided against it for now.

**Comment by SethTisue** [comment]
doh! I forgot about Drone. we don't need Travis here, we have Drone doing PR validation instead. thanks @hejfelix for pointing this out.

I don't know why it didn't catch the bug in #771, though
