### ISSUE TITLE
Clarify sentence in documentation

### ISSUE THREAD

**Issue by Abrasha** [scala/scala.github.com#809]
[Link to page: _Unified types_](http://docs.scala-lang.org/tutorials/tour/unified-types.html)

>`AnyRef` represents reference types. All non-value types are defined as reference types. **Anywhere an `AnyRef` Every user-defined type in Scala is a subtype of `AnyRef`.** 

I believe it should be:
>`AnyRef` represents reference types. All non-value types are defined as reference types. **Every user-defined type in Scala is a subtype of `AnyRef`.**

**Comment by heathermiller** [comment]
This looks good to me @Abrasha! Would you mind PRing it?

Thanks a lot btw!

**Comment by Abrasha** [comment]
@heathermiller Will be done by tomorrow.

**Comment by Abrasha** [comment]
@heathermiller Done in scope of https://github.com/scala/scala.github.com/pull/828
