### ISSUE TITLE
Broken html code on Scala tutorial page

### ISSUE THREAD

**Issue by Esc-Moody-Alam** [scala/scala.github.com#810]
Hi, 

1. The scala code pane does not display properly on this page (see the last para)

http://docs.scala-lang.org/tutorials/tour/classes.html

2. Same issues with this page
http://docs.scala-lang.org/tutorials/tour/traits.html

Kind Regards, 
Moody

**Comment by cooperc0** [comment]
This issue can be resolved by adding a newline before any code block that is not rendering properly. This must have been some change introduced in the markdown parser.

**Comment by heathermiller** [comment]
PR welcome!

**Comment by SethTisue** [comment]
in this repo, kramdown is on 1.11.1, in the scala/scala-lang repo, it's on 1.13.2

jekyll is 3.3.0 here, in scala-lang it's 3.4.0

in general, we want the versions in both repos to be aligned. perhaps a PR upgrading jekyll here would improve the markdown rendering? I don't specifically know if that's a case, but it seems worth a try

**Comment by cooperc0** [comment]
`bundle update` resolves that issue. Maybe consider not checking in the `Gemfile.lock`? Regardless, an update is probably in order.

**Comment by SethTisue** [comment]
> Maybe consider not checking in the Gemfile.lock

I think it's pretty important to have fixed gem versions in version control; the risk of having different contributors unwittingly using different versions of things is too great.

Thanks for the PR! Glad to hear it fixes this problem. 👍

**Comment by heathermiller** [comment]
Thank you again @cooperc0!! We really appreciate the time you took to chase this down and fix it :)
