### ISSUE TITLE
GitHub Pages is still trying to build the site?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#815]
that's what the email I got from GitHub just now seems to indicate:

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> Your site's DNS settings are using a custom subdomain, docs.scala-lang.org, that's not set up with a correct CNAME record. We recommend you set this CNAME record to point at scala.github.io. For more information, see https://help.github.com/articles/using-a-custom-domain-with-github-pages/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by heathermiller** [comment]
Fixed in 8aad0a9af0ca58ee571ec2b262ec562958ea75e7

**Comment by SethTisue** [comment]
nice — so no more error I guess, but the site is still built and published to http://scala.github.io .

at https://github.com/scala/scala.github.com/settings I don't see how to disable that — the branch chooser is grayed out

maybe it's nbd? I guess I see two concerns:

* if the builds stop being successful for whatever reason it could lead to noise we don't want
* search engines might index http://scala.github.io , people might make links to it, etc

**Comment by heathermiller** [comment]
Hilariously, the solution to unpublishing scala.github.io is either deleting the repository or deleting the master branch 😕

**Comment by milessabin** [comment]
Rename master -> tmp -> master?

**Comment by heathermiller** [comment]
Yeah, I thought about that, but can't do it right away. Not until this behemoth is merged: https://github.com/scala/scala.github.com/pull/806

I was just hoping it was a bit simpler than futzing with our branches. As in, click a button and GitHub stops publishing scala.github.io.

**Comment by heathermiller** [comment]
Ok, I wrote GitHub and got the following response:

> Hi Heather,
>
> Thanks for getting in touch!Just so I understand completely, you're trying to disable your GitHub Pages site?
>
>There currently isn't a way to disable pages builds for a repository using the name syntax username.github.io. You can disable pages builds by renaming the repository and making sure that the branch selector under the repository settings is set to "none".
>
>GitHub will then redirect any requests for the old repository name to the new one, so you shouldn't have any interruptions to your process, or any confusion from users.
>
> Hope that helps! Let us know if you have any more questions.
>
> Thanks,
> Thomas

**Comment by SethTisue** [comment]
this was actually fixed by #814
