### ISSUE TITLE
Two broken links in Intruction page of Scala Tour

### ISSUE THREAD

**Issue by bruno-medeiros** [scala/scala.github.com#817]
in http://docs.scala-lang.org/tutorials/tour/tour-of-scala.html

"processing of XML data" link is broken
so is "explicitly typed self references" (should it be http://docs.scala-lang.org/tutorials/tour/self-types.html ?)

**Comment by Abrasha** [comment]
Seems that there is no document that is named `xml-processing.md` (took from 404 link - http://docs.scala-lang.org/tutorials/tour/xml-processing.html). 

So we need an advice to which page it should logically point. Or just remove the link.

**Comment by ashawley** [comment]
Should be fixed with #854

**Comment by heathermiller** [comment]
Indeed it is fixed. Thanks again @ashawley!
