### ISSUE TITLE
Broken links of sidebar in Collections

### ISSUE THREAD

**Issue by jiminhsieh** [scala/scala.github.com#819]
I found out the sidebar of [collections](http://docs.scala-lang.org/overviews/collections/introduction.html) is broken. All of links in sidebar are missed `.html`. But It's fine when you built in local without `.html`. Sorry I am not the expert of frontend, I couldn't figure out the reason.

**Comment by jrudolph** [comment]
That seems to be the case for many of those pages. Also it seems some directories are browsable, e.g. like http://docs.scala-lang.org/overviews/quasiquotes/

Where does the page actually run? It seems it is not served from scala.github.com but from lampsrv1.epfl.ch. Github Pages servers usually seems to take care of these issues.

**Comment by SethTisue** [comment]
As of this week, the site is no longer hosted on GitHub Pages. Reference: #813

**Comment by heathermiller** [comment]
Thanks for reporting. I'm currently working on an overhaul of the doc site, so these things will be fixed shortly. Sorry for any inconvenience!

**Comment by jrudolph** [comment]
I see, thanks. I created #824 which might fix it. As explained there it could (and maybe should) rather be solved with webserver rules.

**Comment by jrudolph** [comment]
Btw. after such a server move it might makes sense for the admin to visit the Google Search console after a while and check the "Crawl Error" page for links that are broken as seen from Google's crawler.
