### ISSUE TITLE
Source links on new API broken

### ISSUE THREAD

**Issue by MarkCLewis** [scala/scala.github.com#835]
I'm pretty certain this isn't the right place for this, but I couldn't think of a better one and this at least deals with documentation. The links to source in the API at scala-lang.org were broken by the move to 2.12.3. This isn't urgent for people who have experience as they can modify the URL to get to a working location, but will be challenging for some and probably has a simple fix.

**Comment by heathermiller** [comment]
What link in particular are you referring to?

**Comment by heathermiller** [comment]
We're in the middle of overhauling docs.scala-lang.org and scala-lang.org. I'm trying to determine if what you're reporting is related to this overhaul (and I'm aware of it), or if there's something that's gone wrong in the release of 2.12.3.

**Comment by MarkCLewis** [comment]
For example, if you go to http://www.scala-lang.org/api/current/scala/collection/immutable/List.html, the source link goes to https://github.com/scala/scala/tree/v2.12.3/src/library/scala/collection/immutable/List.scala#L1, which gives a 404. If I change the 3 to a 2 it is happy and I get the source for 2.12.2.

**Comment by SethTisue** [comment]
sadly, this happens every time — building the release changes the doc links but the new URLs don't actually exist until we announce. we plan to announce later today

**Comment by MarkCLewis** [comment]
I hadn't noticed it before. Now that I know, I won't take up people's time if I see it again in the future. I really appreciate all the hard work that all of you put into Scala and the Scala ecosystem.

**Comment by SethTisue** [comment]
thanks for the report! our bad that we still don't have a real fix for this...

**Comment by retronym** [comment]
The v2.12.3 tag has now been pushed, so the links no longer dangle.

**Comment by som-snytt** [comment]
Thanks for courageously pushing 2.12.3. I think all the publications and web site updates require some chutzpah.
